-- Drop COLUMN BOOK_ID from the BOOK table
ALTER TABLE BOOK
DROP COLUMN BOOK_ID;

-- Change the data type of BOOK_ID in the BOOK table to VARCHAR(100)
ALTER TABLE BOOK
    ADD COLUMN BOOK_ID VARCHAR(100);


-- Change the data type of MOBILE_NUMBER in the USERS table to VARCHAR(15)
ALTER TABLE USERS
ALTER COLUMN MOBILE_NUMBER TYPE VARCHAR(15);

-- Change the data type of EMAIL in the USERS table to VARCHAR(20)
ALTER TABLE USERS
ALTER COLUMN EMAIL TYPE VARCHAR(20);
